<?php
use Magento\Framework\Escaper;
use Meiko\EditOrder\Block\Order\Info;
use Meiko\EditOrder\ViewModel\OrderExportView;
/** @var  Escaper $escaper */
/** @var OrderExportView $viewModel */
?>
<?php
/** @var $block Info */
?>
<?php $_order = $block->getOrder();
$orderId = $block->getOrder()->getData('entity_id');
$newItem = $block->getOrderDetails($orderId);
?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()) : ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?= $escaper->escapeHtml(__('Shipping Address')) ?></span></strong>
<?php if (is_object($newItem) && ($newItem->getStatus() != "Storniert") && ($newItem->getStatus() != "Annulée")) { ?>
                <a style="margin-right: 10px" href="<?= $block->editAddress() ?>"><?= __('Edit Delivery Address') ?> <i style="margin-left:5px" class="fa fa-edit"></i></a>
                <?php } ?>
                <div class="box-content">
                    <address><?= /* @noEscape */
                        $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                </div>
            </div>
            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?= $escaper->escapeHtml(__('Shipping Method')) ?></span>
<?php if (is_object($newItem) && ($newItem->getStatus() != "Storniert") && ($newItem->getStatus() != "Annulée")) { ?>
                    <a href="<?= $block->shippingMethod() ?>"><?= __('Edit Shipping Method') ?><i style="margin-left: 5px" class="fa fa-edit"></i></a>
                    <?php } ?>
                </strong>
                <div class="box-content">
                    <?php if ($_order->getShippingDescription()) : ?>
                        <?= $escaper->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else : ?>
                        <?= $escaper->escapeHtml(__('No shipping information available')) ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= $escaper->escapeHtml(__('Billing Address')) ?></span>
<?php if (is_object($newItem) && ($newItem->getStatus() != "Storniert") && ($newItem->getStatus() != "Annulée")) { ?>
                <a style="margin-right: auto" href="<?= $block->billingAddress() ?>"><?= __('Edit Billing Address') ?> <i style="margin-left: 5px" class="fa fa-edit"></i></a>
                <?php } ?>
            </strong>
            <div class="box-content">
                <address><?= /* @noEscape */
                    $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= $escaper->escapeHtml(__('Payment Method')) ?></span>
<?php if (is_object($newItem) && ($newItem->getStatus() != "Storniert") && ($newItem->getStatus() != "Annulée")) { ?>
                <a href="<?= $block->paymentMethod() ?>"><?= __('Edit Payment Method') ?><i style="margin-left: 5px" class="fa fa-edit"></i></a>
                <?php } ?>
            </strong>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
